### ISSUE TITLE
Pydanticgen range generator, to support any_of and have a better generation system overall

### ISSUE THREAD

**Issue by daniel-ji** [linkml/linkml#2251]
#### Refactored `generate_slot`

```
generate_slot(SlotDefinition, ClassDefinition) -> SlotResult:
	- calls generate_slot_range(SlotDefinition) to output a RangeResult. RangeResult has a range string (type PydanticAnnotation) 
	- The SlotResult gets created then SlotResult.merge(RangeResult)
		- how the merge actually happens (pretty simple function): the `SlotResult.attribute.annotation` is just getting set to `RangeResult.range` 
		- this will be rendered properly because it will be found through a recursive search through the nested fields (we don't have to worry about this)
	- return SlotResult
```

#### New `generate_slot_range`

```
generate_slot_range: (SlotDefinition, ClassDefinition (if necessary)) -> RangeResult:
	- creates an original RangeResult based on the slot's range field (or an empty one if there is none) with RangeGenerator.build()
		- assuming predefined_values is already incorporated before doing this 
	- loop through all the `any_of` fields and also creates RangeResult with RangeGenerator and then merges the newly created RangeResult with the original RangeResult by calling RangeResult.merge(RangeResult)
		- really just kind of compounding all the RangeResults into one
		- RangeGenerator does the initial generation and RangeResult then merges 
	return final compounded / smashed-together RangeResult
```

#### Task Set 1a:
- [ ] create a PydanticAnnotation class that has everything that's necessary for annotation.py.jinja
- [ ] create the annotation.py.jinja template to render the Pydantic code correctly based on the provided PydanticAnnotation fields

#### Task Set 1b: 
- [ ] Move everything out of generate_slot that is related to range and put it in the build() function of a Pydanticgen implementation of RangeGenerator
- [ ] complete the Pydantic RangeGenerator.build() function so that now it's actually outputting proper `RangeResult`s
	- ensure the RangeResult.range (of type str/PydanticAnnotation) has the correct values being stored in the PydanticAnnotation fields (so that the annotation.py.jinja rendering is receiving the right values to render)

#### Task Set 2 (blocked by Task Set 1s):
- [ ] build the merge() function for a Pydantic RangeResult implementation
- [ ] build generate_slot_range()

#### Task Set 3 (blocked by Task Set 2):
- [ ] Create capability to merge RangeResult into SlotResult
- [ ] Tie everything together in generate_slot() and call generate_slot_range() in generate_slot()

#### In general:
- [ ] Write tests for everything and make sure past tests don't fail
- [ ] Somewhere along the line, (anytime after Task Set 1a I feel like), remove things from PydanticAttribute that are handled by PydanticAnnotation, and move everything else into a PydanticField class

Questions/comments:
- Range is inherently different from Attribute, so although this solution does account for any_of range, how about any_of without range? say we have some any_of without any range attributes, but with minimum and maximum value attributes each or min_length and max_length
- Should we prefix all Pydantic implementations of these common generators / results class with "Pydantic"? For example, the Pydantic implementation of RangeGenerator would be "PydanticRangeGenerator"
- I could help with a writeup on how all it works (generators, results, and templating classes), if you'd like (so the learning curve might be a bit easier for whoever in the future may be needing to use learn / use this)
