### ISSUE TITLE
markdowngen improvements

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#245]
## Ungrouped
* [ ] 1. hyperlink CURIEs universally
* [ ] 2. add option to show all slots for a class as a table rather than indented lists. Particular important for classes with many slots (e.g MIxS)
* [ ] 3. integrate instance/test data into documentation
* [x] 4. improve the linkml-model docs; make them an exemplar
 * e.g. this looks rubbish https://linkml.github.io/linkml-model/docs/home/
* [ ] 5. make sure all info is rendered
 * `recommended`
 * mix/max value
 * ...
* [ ] 19. Differentiating between Entity, Association, Slot, Relation and Property during export from biolinkml. This could be handled by creating folders for each, and exporting the markdown into these folders. (#18)
* [ ] 20. CURIE mappings from YAML should be in markdown export (currently missing). (#18)
* [ ] 30. The title in each markdown should be camelcase instead of sentence case. For example, it should be Class: NamedThing instead of Class: named thing. (#18)
* [ ] 31. When generating from multiple modules, combine in a docs/ dir rather than a different dir for each module (#69).
* [ ] 32. "See also" should be more prominent (#112)
* [ ] 34. Types page should show `uri` value. E.g. https://w3id.org/linkml/Uriorcurie should show this is mapped to xsd:anyURI

### Deprecated elements
  * [ ] 6. render in strikethrough
  * [ ] 7. change ordering such that these are placed last
### Induced slots #144   
  * [ ] 8. have option to not show induced class-specific slots
  * [ ] 9. even if induced slots are retained, include explanatory text
    * e.g. someone landing here will be confused https://linkml.github.io/linkml-model/docs/class_definition_is_a
  * [ ] 10. improve search. Remove dupes, e.g. https://linkml.github.io/linkml-model/docs/search.html?q=pv_formula
### Mixins
  * [ ] 11. slot mixins should be rendered same as class mixins - place at bottom of list
### Enums
  * [ ] 12. enum page should show uses of enum
  * [ ] 13. what is the blank table doing here?  https://linkml.github.io/linkml-model/docs/pv_formula_options
### Imports
  * [ ] 14. create a separate index for each imported module
     - only do when mergeimports is false
     - each index should visually indicated imported vs in-module classes
  * [ ] 15. visualize import closure
### Viz
  * [ ] 16. optionally follow inline-closure when generating yUML
  * [ ] 17. for ER-style models, show ER-style diagram, and "hop-over" relationship (see gocam docs)
  * [ ] 18. use obographviz to show whole-schema graphic
### Status
  * [ ] 33. Color based on `linkml:status`

**Comment by joeflack4** [comment]
### Subtask:  hyperlink CURIEs universally
@cmungall It looks to me like this is done already. I'm just checking the "kitchen_sink" test outputs and how things are handled in `markdowngen`. Every output that contains a CURIE reference is wrapped in a URL, from what I can see.

Can you confirm that this task is completed to satisfaction? If not, is there somewhere that CURIEs are not being hyperlinked? 

<img width="955" alt="Screen Shot 2021-09-23 at 6 02 28 PM" src="https://user-images.githubusercontent.com/13045020/134590693-49ab32ff-8063-4804-b663-b1eb92a43fc1.png">
<img width="1325" alt="Screen Shot 2021-09-23 at 6 05 36 PM" src="https://user-images.githubusercontent.com/13045020/134590696-b1074239-5321-4b42-9baa-c012c306cbfd.png">
<img width="801" alt="Screen Shot 2021-09-23 at 6 07 58 PM" src="https://user-images.githubusercontent.com/13045020/134590697-d6a51f4a-dfb6-415f-b5f4-c70ae47acf4f.png">

**Comment by joeflack4** [comment]
RE: "deprecated elements"."render in strikethrough": I added comments and review in #366

**Comment by joeflack4** [comment]
RE: **hyperlink CURIEs universally**

@cmungall Hey Chris. At the moment we're both in the LinkML meeting; I'll bring this up if there's time. I was looking at the CURIE issue and I'm wondering if this is an issue with **markdowngen** or is it with how **Sphinx** creates our docs? If Sphinx, I'm not sure how to do this way to programmatically, and I don't know if it involves markdowngen.
<img width="859" alt="Screen Shot 2021-09-24 at 4 32 53 PM" src="https://user-images.githubusercontent.com/13045020/134736557-28adee28-a450-479a-8d9c-3a059c23264d.png">

**Comment by joeflack4** [comment]
@gaurav @cmungall  Ok, I looked again and learned a bit more.

## CURIEs in Sphinx-generated HTML
This is not part of the scope of this issue, correct?

But if it is desired to have CURIEs in the documentation wrapped in hyperlinks, perhaps that should be added to a separate (Sphinx/docs-related) issue? I am not sure how to do this programmatically using Sphinx. Below is just an example of some CURIEs in the `sphinx/` dir. In order to wrap these in a hyperlink, I think I would have to do this manually for each instance in which they appear?
<img width="916" alt="Screen Shot 2021-09-24 at 5 12 45 PM" src="https://user-images.githubusercontent.com/13045020/134741054-18f75488-a9cb-413b-bc56-ec68883ac087.png">

## CURIEs in markdowngen-generated markdown
As for `markdowngen`, I mentioned that it looks like there are already hyperlinks. 

For example, when I look at the markdowngen test outputs, all of them have hyperlinks:
<img width="955" alt="Screen Shot 2021-09-23 at 6 02 28 PM" src="https://user-images.githubusercontent.com/13045020/134590693-49ab32ff-8063-4804-b663-b1eb92a43fc1.png">

And when I run markdowngen manually (`gen-markdown core.yaml -d hello`), I also get CURIEs wrapped in hyperlinks.

Source file:
<img width="472" alt="Screen Shot 2021-09-24 at 5 19 26 PM" src="https://user-images.githubusercontent.com/13045020/134741057-8cbe9833-b07f-4077-986b-7eebd8b1dee3.png">

Result:
<img width="1225" alt="Screen Shot 2021-09-24 at 5 20 20 PM" src="https://user-images.githubusercontent.com/13045020/134741058-195c373d-650a-47f5-a460-4ae21b2c9efb.png">

However, what I just realized is that I think the URL is wrong. In this final screenshot, I see that there is something that says `default_prefix: core`. And it looks like when it expands the CURIE for `prov:Activity` in this example, it is using the URL for the `core` prefix, not the `prov` prefix.

---

## Questions
So my questions are:
1. Does it indeed look to you guys (looking at the resulting markdowngen created files in my screenshot) that markdowngen is already wrapping CURIEs with URLs? I don't think my eyes are deceiving me. I must just be misunderstanding something.
2. Is it expected behavior that the `core` prefix is being used for expansion rather than the `prov` prefix? I think this is a bug.
2.2: If this is expected behavior, does that mean that this sub-task (" hyperlink CURIEs universally") is already done?
2.3: If this is not expected behavior, then I suppose all I need to do is fix the bug and then my work is done? (other than Sphinx)

**Comment by cmungall** [comment]
yes sub-issues may be good

I unchecked the strikethrough one as unfortunately this doesn't work unless you install the extension:

https://github.com/mkdocs/mkdocs/issues/868

I think making the extension part of the pipenv requirements is sufficient?

**Comment by cmungall** [comment]
closing this as new development is now on docgen
