### ISSUE TITLE
(1) README updates, (2) potential restructuring

### ISSUE THREAD

**Issue by joeflack4** [linkml/linkml#762]
## Summary
The current `README.md` links to the [LinkML docs](https://linkml.io/linkml/), which is good, but it does not say anything about what the repo `linkml` is for. This is in contrast with other LinkML repositories, where the purpose of the repo is clear based on its home page via the _readme_. In addition, I suggest some restructurings.

## Proposed restructurings
I don't have much bandwidth for LinkML right now, so it's easy for me to suggest these changes. I understand that it could be a little time consuming to make them. But here's what I'm thinking.

[This page](https://linkml.io/linkml/developers/organization.html) lists out in bullets the current function of `linkml/linkml` at this time.

My suggestions:
1. **generators** and **dateutils**: Move into either **(a)** 1 new repo, `linkml-utilties` or `linkml-tools`, or, **(b)** create 2 repos, one for `linkml-generators`, and the other for `linkml-utilities` (can put 'dateutils' in there).
2. **documentation**: Either **(a)** leave it in `linkml/linkml`, or **(b)** move it to a new repo `linkml-documentation`. I have a slight preference towards (b). If (b), then the new purpose of `linkml/linkml` would be for management purposes, i.e. issues, projects, actions (if applicable), and discussion/wiki if those ever become worth using.

## Tasks
- [ ] 1. Decide if `linkml/linkml` needs any restructuring.
- [ ] 2. Do that restructuring, if so.
- [ ] 3. Update _readme_ (at each repo, if split) to explain the function of the repository(s).

## Related issues
1. Related to a similar discussion at TCCM, which has similar issues: https://github.com/HOT-Ecosystem/tccm/issues/7
2. #759

**Comment by nlharris** [comment]
Hi Joe, thanks for your suggestions! I unassigned Chris; we don't get to assign tasks to @cmungall 🙂

Did you see my ticket #759 that relates to this, and the linked PRs?

**Comment by joeflack4** [comment]
@nlharris I did see that, thanks. I looked at it, and I think my issue is a subset of that. I'll add a link to your issue to the OP of this one.

@cmungall asked me to open an issue here. Let me know if either of you guys / anyone would prefer me to split this into 2 issues (docs and restructuring), or keep as one.

**Comment by cmungall** [comment]
I think these are good points. But restructuring now will be hard. There are many projects with `linkml` in their pyproject/requirements.txt/pipfile/setup.py. Renaming this will be a big breaking change (assuming we change the package name in pypi)

I don't think it's wrong in principle to have a repo and org name be the name; e.g

https://github.com/RDFLib/rdflib/

It seems the main point of confusion is people arriving at the README on the linkml repo. My intent was to guide them to the docs as soon as possible (remember many linkml users will not even need to look at the github site)

This is what we have now with @nlharris's addition:

LinkML is a linked data modeling language following object-oriented and ontological principles. LinkML models are typically authored in YAML, and can be converted to other schema representation formats such as JSON or RDF.

This repo holds the tools for generating and working with LinkML. For the LinkML schema (metamodel), please see https://github.com/linkml/linkml-model

The complete documentation for LinkML can be found here:

[linkml.io/linkml](https://linkml.io/linkml)

**Comment by joeflack4** [comment]
Your point in that this would be a heavy lift is duly noted!

I created this issue on your ask, but perhaps that one bit really is enough: 
> This repo holds the tools for generating and working with LinkML. For the LinkML schema (metamodel), please see https://github.com/linkml/linkml-model

Although what you linked on [this page](https://linkml.io/linkml/developers/organization.html) helped me understand things better. Maybe it's just the way my brain works:
> [linkml](https://github.com/linkml/linkml-model)
> - [generators](https://linkml.io/linkml/generators/index.html#generators)
> - datautils
> - this documentation

**Comment by nlharris** [comment]
So should we close this issue?
