### ISSUE TITLE
document the "role" element in the meta model and how it should be used. 

### ISSUE THREAD

**Issue by sierra-moxon** [linkml/linkml#802]
"role" element does not have a description https://linkml.io/linkml-model/docs/role/

**Describe the solution you'd like**

- [ ] a description for the "role" element
- [ ] a FAQ pointer possibly to the role element description (hard to tell if the FAQ + examples of modeling component use should go in a FAQ in LinkML doc, or close to the element itself in linkml-model itself.  As a user I would first locate the linkml-model doc and if I couldn't get what I needed there, I'd go look for a FAQ, but mmv.  
- [ ] a couple of good examples (we might be able to lift these from biolink-model) 

**How important is this feature?** Select from the options below:
• Low - it's an enhancement but not crucial for work

**When will use cases depending on this become relevant?** Select from the options below:
• Long-term - 6 months - 1 year

**Additional context**
[Add any other context or screenshots about the feature request here.](https://github.com/biolink/biolink-model/issues/488)

**Comment by cmungall** [comment]
this would be a good FAQ entry to have

currently AFAIW only biolink uses this. The basic intuition is to give a name to a slot that is inherited from a generic class in the context of a subclass, without actually renaming it

**Comment by sierra-moxon** [comment]
now role has a description.
