### ISSUE TITLE
Expand docgen (epic)

### ISSUE THREAD

**Issue by sierra-moxon** [linkml/linkml#925]
We'd like to expand docgen to both cover the use cases currently implemented for markdowngen and expand the functionality in the image generation via mermaid to make the default autogenerated docs maximally helpful for users to explore the model. 

The checkboxes here indicate a ticket to create in the Expand Docgen project. Please edit the original post with more features and check off tickets that have been created already.

- [x] Link classes in mermaid diagrams such that if a user clicks on the class, it navigates to that class doc page with the image recentered on the clicked class
- [x] Metadata currently in LinkML Source section on slot pages should be displayed promentantly and linked.  For example, https://microbiomedata.github.io/nmdc-schema/GOLD_sample_identifiers/
Ideally, all knowledge that appears in the LinkML Source section would be displayed above with links to the documentation pages of the model elements it refers to.
- [x] Whenever a page is a mixin or abstract, simply show a table of all descendant elements.

**Comment by sierra-moxon** [comment]
The checkboxes here indicate a ticket to create in the `Expand Docgen` project.   Please edit the original post with more features and check off tickets that have been created already.
